#!/bin/bash

cd "${DDEV_APPROOT}/nextjs"
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

echo "Starting Next.js build..."
HOST=0.0.0.0 PORT=3333 npm run build
